language: bash
sudo: false
cache:
  - apt
os:
  - linux
before_script:
  - source ./tests/setup_bats.sh
addons:
  hosts:
    - travis.dev
env:
  - TRAVIS_CI_RUN=true GIT_SSH='ssh -o StrictHostKeyChecking=no' GIT_AUTHOR_NAME='Travis CI' GIT_AUTHOR_EMAIL='travis@example.com'
script:
  - bats tests
notifications:
  email:
    on_success: never
